logging:
  level:
    com.brh.p2p.nifa: debug

server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:oracle:thin:@10.211.17.91:1521/brh
    username: new_portal
    password: new5020
