logging:
#  file: runlog
  level:
    root: info

server:
  port: 8080

spring:
  profiles:
    active: @activeProfile@
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
  freemarker:
    template-loader-path: classpath:templates
#  mvc:
#    static-path-pattern: classpath:static

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.brh.p2p.nifa.data.entity
mapper:
  mappers: com.brh.p2p.nifa.data.repository
  not-empty: false
  identity: Oracle

#pagehelper
pagehelper:
    helperDialect: Oracle
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

nifa:
  transfer-service:
    host: 127.0.0.1
    port: 8888
    upload-url: http://${nifa.transfer-service.host}:${nifa.transfer-service.port}/nifa/sftp/upload?systemid=1&stype=24&sourcePath=%s
    download-url: http://${nifa.transfer-service.host}:${nifa.transfer-service.port}/nifa/sftp/download?systemid=1&stype=24&sourcePath=%s&targetPath=%s
  work-dir:
    datafiles: ${user.dir}/datafiles
#    feedback: ${user.dir}/feedback
